networks:
  rss-telegram:
    driver: bridge

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    networks:
      - rss-telegram
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test

  app:
    image: node:23-alpine
    ports:
      - 3001:3001
    working_dir: /app
    networks:
      - rss-telegram
    volumes:
      - .:/app
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      AUTH_SECRET: ${AUTH_SECRET}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_SESSION_KEY: ${TELEGRAM_SESSION_KEY}
      BOT_CLIENT_TOKEN: ${BOT_CLIENT_TOKEN}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      RSS_FEED_URL: ${RSS_FEED_URL}
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mongo
