@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OWQzZGE3My03YjVjLTRhOTQtOGQyYy1hM2UxNTFmNDk1OTgiLCJpYXQiOjE3MzA2NzAyNDIsImV4cCI6MTczMDc1NjY0MiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIn0.KYGumXofMwXkBSW1UY1564q4_PgfS1z9GnWtsoP9Fqc

# Sign Up
POST {{url}}/auth/signup
Content-Type: application/json

{
  "password": "123",
  "email": "test@test.com"
}

###

POST {{url}}/auth/signin
Content-Type: application/json

{
  "password": "123",
  "email": "test@test.com"
}

###
POST {{url}}/channels
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "channelId": "nikitonsky_pub"
}

###
GET {{url}}/channels/nikitonsky_pub/posts
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{url}}/telegram
Content-Type: application/json
Authorization: Bearer {{token}}

{}
